name: Manual Token Generation

on:
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest  # use self-hosted if needed for browser-based login
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credential.json and token.json
        run: |
          mkdir secrets
          echo '${{ secrets.CREDENTIAL_JSON }}' > secrets/credential.json

      - name: Run Auth Script
        id: run_auth
        run: python scripts/manual_auth.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: secrets/credential.json

      - name: Update TOKEN_JSON secret
        if: steps.run_auth.outputs.refreshed == 'true'
        uses: gliech/create-github-secret-action@v1
        with:
          pa: ${{ secrets.GITHUB_TOKEN }}
          name: TOKEN_JSON
          value: ${{ steps.run_auth.outputs.refreshed_token }}

         
     